### ISSUE TITLE
Security Data Issues Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [Vishal1419/security-system#2]
Hi,<br><br>url : https://github.com/Vishal1419/security-system/blob/976355c32987e4b058b21273bfad058c2b19c43e/config/index.js <br><br>You have commit that need to remove from the github history<br>attacker can see it and use it ...<br><br>encrypt your secrets !!!!<br><br>Our Bug Help you to be more Secure and protect your data ?<br>Buy me a coffee (or more likely a beer)<br>https://www.paypal.com/paypalme/bugbounty1/150USD<br>https://www.buymeacoffee.com/bugbounty<br>☕☕☕☕☕

**Comment by Vishal1419** [comment]
Thank you @shaybenb for mentioning it. But this project was just for learning purposes and the password is also a fake one, which i do not use anywhere else. So, its not an issue for me.

Thank you and have a nice day!
